WebApplication1/Controllers/ConfigController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using PrintManagement.Common.Models;
using PrintManagement.Common.Repositories;
using PrintManagementApp.Filters;
using PrintManagementApp.Utilities;

namespace PrintManagementApp.Controllers
{
    #region

    #endregion
    [SessionExpireFilter]
    public class ConfigController : Controller
    {

        #region
        private readonly Repository irepo;
        private readonly Utility util;
        #endregion

        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="HomeController" /> class.
        /// </summary>
        /// <param name="IRepository">The tenants repository.</param>
        public ConfigController()
        {
            irepo = new Repository();
            util = new Utility();
        }
        #endregion

        public async Task<ActionResult> Index()
        {
            try
            {
                var OrderConfigModel = await irepo.GetAllOrderConfiguration();
                return View(OrderConfigModel);
            }
            catch (Exception e)
            {
                return View(e.Message);
            }
        }

        public async Task<ActionResult> AddConfig()
        {
            try
            {
                ViewBag.OrderItem = await irepo.GetAllOrderItem();
                ViewBag.AllProductItem = await irepo.GetAllProductItem();
                ViewBag.PrintingColor = await irepo.GetAllPrintingColour();
                ViewBag.Papersize = await irepo.GetAllPaperSize();
                ViewBag.PaperGSM = await irepo.GetAllPaperGSM();
                ViewBag.PaperSide = await irepo.GetAllPaperSide();
                ViewBag.LedgerFolio = await irepo.GetAllLedgerFalio();
                ViewBag.Customers = await irepo.GetAllCustomer();
                ViewBag.paperQuality = await irepo.GetAllPaperQuality();
                ViewBag.ItemDisplayConfig = await irepo.GetAllItemDisplayConfig();
                ViewBag.BtnName = "ADD";
                return View();
            }
            catch (Exception e)
            {
                return View(e.Message);
            }
        }

        public async Task<ActionResult> UpdateConfig()
        {
            try
            {
                ViewBag.AllProductItem = await irepo.GetAllProductItem();
                ViewBag.PrintingColor = await irepo.GetAllPrintingColour();
                ViewBag.Papersize = await irepo.GetAllPaperSize();
                ViewBag.PaperGSM = await irepo.GetAllPaperGSM();
                ViewBag.PaperSide = await irepo.GetAllPaperSide();
                ViewBag.LedgerFolio = await irepo.GetAllLedgerFalio();
                ViewBag.Customers = await irepo.GetAllCustomer();
                ViewBag.paperQuality = await irepo.GetAllPaperQuality();
                ViewBag.BtnName = "UPDATE";
                return View("AddConfig");
            }
            catch (Exception e)
            {
                return View(e.Message);
            }
        }

        
        public async Task<int> InsertConfig(OrderConfigurationModel obj)
        {
            obj.CreatedBy = Convert.ToString(Session["AccountName"]);
            obj.CreatedDate = DateTime.Now;
            var i =await util.getdata(obj);
            if (i.OrderConfigurationId == 1)
            {
                return 1;
            }
            else if(i.OrderConfigurationId==0)
            {
                var orderConfig = irepo.AddOrderConfiguration(obj);
                return 0;
            }
            return 1;
        }

    }
}

WebApplication1/Controllers/JobController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using PrintManagement.Common.Models;
using PrintManagement.Common.Repositories;
using PrintManagementApp.Filters;
using PrintManagementApp.Utilities;

namespace PrintManagementApp.Controllers
{
    #region

    #endregion

    [SessionExpireFilter]
    public class JobController : Controller
    {

        #region
        private readonly Repository irepo;
        private readonly Utility util;
        #endregion
        #region Constructors

        /// <summary>
        /// Initializes a new instance of the <see cref="JobController" /> class.
        /// </summary>
        /// <param name="IRepository">The tenants repository.</param>
        public JobController()
        {
            irepo = new Repository();
            util = new Utility();
        }
        #endregion

        public async Task<ActionResult> Index()
        {
            try
            {
                ViewBag.OrderItem = await irepo.GetAllOrderItem();
                ViewBag.AllProductItem = await irepo.GetAllProductItem();
                ViewBag.PrintingColor = await irepo.GetAllPrintingColour();
                ViewBag.Papersize = await irepo.GetAllPaperSize();
                ViewBag.PaperGSM = await irepo.GetAllPaperGSM();
                ViewBag.PaperSide = await irepo.GetAllPaperSide();
                ViewBag.LedgerFolio = await irepo.GetAllLedgerFalio();
                ViewBag.Customers = await irepo.GetAllCustomer();
                ViewBag.paperQuality = await irepo.GetAllPaperQuality();
                ViewBag.ItemDisplayConfig = await irepo.GetAllItemDisplayConfig();
                return View();
            }
            catch (Exception e)
            {
                return View(e.Message);
            }
        }

        public async Task<ActionResult> Report()
        {
            try
            {
                var OrderItemModel = await irepo.GetAllOrderItem();
                return View(OrderItemModel);
            }
            catch (Exception e)
            {
                return View(e.Message);
            }
        }

        public async Task<ActionResult> Orders()
        {
            try
            {
                var OrderItemModel = await irepo.GetAllOrderItem();
                return View(OrderItemModel);
            }
            catch (Exception e)
            {
                return View(e.Message);
            }
        }

        public async Task<int> saveCustomer(OrderItemModel obj)
        {
            if (obj.OrderId != 0)
            {
                Console.WriteLine(obj.OrderId + "" + "is the order id");
                obj.UpdatedBy = Convert.ToString(Session["AccountName"]);
                obj.UpdatedDate = DateTime.Now;
                if (obj.JobProcessType == "Order Confirm")
                {
                    if (obj.CustomerId == null)
                    {
                        CustomerModel c = new CustomerModel();

                        c.CreatedBy = Convert.ToString(Session["AccountName"]);
                        c.FirstName = obj.FirstName;
                        c.LastName = obj.LastName;
                        c.PhoneNumber = obj.PhoneNumber;
                        c.CreatedDate = obj.CreatedDate;
                        c.Email = obj.Email;
                        var a = await irepo.AddCustomer(c);
                        obj.CustomerId = a;
                    }
                }
                var OrderItemModel = irepo.UpdateOrderItem(obj, obj.OrderId);
                return 1;
            }
            else
            {
                Console.WriteLine("no orderid" + "" + "so creating new");
                obj.CreatedBy = Convert.ToString(Session["AccountName"]);
                obj.CreatedDate = DateTime.Now;
                if (obj.JobProcessType == "Order Confirm")
                {
                    if (obj.CustomerId == null)
                    {
                        CustomerModel c = new CustomerModel();

                        c.CreatedBy = Convert.ToString(Session["AccountName"]);
                        c.FirstName = obj.FirstName;
                        c.LastName = obj.LastName;
                        c.PhoneNumber = obj.PhoneNumber;
                        c.CreatedDate = obj.CreatedDate;
                        c.Email = obj.Email;
                        var a = await irepo.AddCustomer(c);
                        obj.CustomerId = a;
                    }
                }
                var OrderItemModel = irepo.AddOrderItem(obj);
                return 1;
            }

        }

        public void customer(CustomerModel obj)
        {
            var CustomerAdd = irepo.AddCustomer(obj);
        }

        public async Task<JsonResult> CalculateTaxes(OrderItemModel obj)
        {
            TaxViewModel t = new TaxViewModel();
            t = await util.GetTaxAmt(obj);
            return Json(t, JsonRequestBehavior.AllowGet);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body class="@ViewBag.Class">
    <div class="header-cont">
        <div class="menu-cont">
            <div class="menu-text">Menu</div>
        </div>
        <div class="heading-cont">
            <div class="heading-text">Print Management System</div>
        </div>
        <div class="profile-cont">
            <div class="profile-user">Hi @Session["AccountName"]</div>
            <div class="profile-logout">@Html.ActionLink("LogOut", "Login", "Account")</div>
        </div>
    </div>
    <div class="side-navbar @Session["Roles"]">
        <div class="menu-text">Menu</div>
        <div class="menu-item Orders">@Html.ActionLink("Orders", "Orders", "Job")</div>
        <div class="menu-item Jobs">@Html.ActionLink("Jobs", "Index", "Job")</div>
        @if (@Session["Roles"] != null && (string)@Session["Roles"] == "admin")
        {
            <div class="menu-item Config">@Html.ActionLink("Configurator", "Index", "Config")</div>
            <div class="menu-item Report">@Html.ActionLink("Report", "Report", "Job")</div>
        }
    </div>

    <div class="body-cont">
        <div class="body-content">
            @RenderBody()
        </div>
    </div>
    <div class="loader fa fa-spinner fa-spin"></div>
    <div class="loading-mask"></div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css">
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <script src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
    <script src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <link href="~/Content/DataTables/css/dataTables.jqueryui.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/1.10.16/css/dataTables.jqueryui.min.css"></script>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <script src="https://cdn.datatables.net/1.10.16/css/dataTables.jqueryui.min.css"></script>
    <script src="~/Scripts/DataTables/dataTables.jqueryui.js"></script>
    <script src="~/Scripts/DataTables/dataTables.jqueryui.min.js"></script>
    <script src="~/Scripts/DataTables/responsive.jqueryui.min.js"></script>
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="~/Scripts/jquery-3.2.1.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/dataTables.jqueryui.min.js"></script>

    <script src="~/Scripts/tableExport.jquery.plugin-master/tableExport.js"></script>
    <script src="~/Scripts/tableExport.jquery.plugin-master/html2canvas.js"></script>
    <script src="~/Scripts/tableExport.jquery.plugin-master/jquery.base64.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.js"></script>
    <script src="~/Scripts/custom.js"></script>
    @RenderSection("scripts", required: false)
    <div class="col-sm-2"></div>

    <footer>
        <div class="footer-cont">Print Management System. A product of <a target="_blank" href="http://www.vuedata.com/">VueData Technologies</a></div>
    </footer>
</body>
</html>